export interface MenuItem {
  id: string
  name: string
  description: string
  price: number
  category: string
  photo: string
  bestseller?: boolean
}

export const MENU: MenuItem[] = [
  // ── BIRYANI & RICE ──────────────────────────────────────────
  {
    id: '9170d644-5efd-4147-a094-f0f9c50c55cc',
    name: 'Chicken Biryani',
    description: 'Aromatic basmati rice slow-cooked with tender chicken, whole spices, caramelised onions and saffron.',
    price: 160,
    category: 'Biryani',
    photo: '/chicken-biryani.png',
    bestseller: true,
  },
  {
    id: '240ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Chicken Tikka Rice',
    description: 'Flavourful basmati rice served with chunks of roasted chicken tikka and spiced gravy.',
    price: 240,
    category: 'Biryani',
    photo: '',
  },
  {
    id: 'c01ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Chicken Lollipop Rice',
    description: 'Basmati rice served alongside crispy chicken lollipops with spiced gravy.',
    price: 220,
    category: 'Biryani',
    photo: '',
  },
  {
    id: 'c02ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Chicken Tangdi Rice',
    description: 'Aromatic rice served with a whole marinated chicken tangdi, slow-cooked with spices.',
    price: 250,
    category: 'Biryani',
    photo: '',
  },
  {
    id: 'c03ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Chicken Barra Rice',
    description: 'Fragrant basmati rice paired with juicy marinated chicken barra pieces.',
    price: 270,
    category: 'Biryani',
    photo: '',
  },
  {
    id: 'c04ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Chicken Leg Rice',
    description: 'Basmati rice served with a whole spiced chicken leg, dum-cooked to perfection.',
    price: 220,
    category: 'Biryani',
    photo: '',
  },
  {
    id: '250ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Mutton Biryani (2pcs)',
    description: 'Rich basmati rice slow-cooked with 2 tender mutton pieces, saffron and aromatic spices.',
    price: 250,
    category: 'Biryani',
    photo: '/mutton-korma.png',
  },
  {
    id: 'c05ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Mutton Biryani (3pcs)',
    description: 'Rich basmati rice slow-cooked with 3 tender mutton pieces, saffron and aromatic spices.',
    price: 300,
    category: 'Biryani',
    photo: '',
  },
  {
    id: '130ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Biryani Rice',
    description: 'Plain aromatic basmati rice cooked in biryani stock and saffron.',
    price: 130,
    category: 'Biryani',
    photo: '',
  },

  // ── FRY ─────────────────────────────────────────────────────
  {
    id: 'b09ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Chicken Leg / Chest',
    description: 'Crispy deep-fried chicken leg or chest piece marinated in red chili paste and spices.',
    price: 140,
    category: 'Fry',
    photo: '',
  },
  {
    id: 'b10ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Chicken Lollipop (4pcs)',
    description: 'Crispy fried chicken wings shaped like lollipops, coated in a spicy batter.',
    price: 180,
    category: 'Fry',
    photo: '',
  },
  {
    id: 'b11ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Chicken Tikka Fry (5pcs)',
    description: 'Spiced chicken chunks pan-fried with green chilies, onions and chaat masala.',
    price: 220,
    category: 'Fry',
    photo: '',
  },
  {
    id: 'b12ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Chicken Kaleji',
    description: 'Spicy chicken liver dry fry with ginger, garlic and fresh green herbs.',
    price: 130,
    category: 'Fry',
    photo: '',
  },

  // ── GRAVY ────────────────────────────────────────────────────
  {
    id: 'b01ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Butter Chicken',
    description: 'Classic murgh makhani in rich, buttery tomato sauce — available bone-in or boneless.',
    price: 250,
    category: 'Gravy',
    photo: '/butter-chicken.png',
    bestseller: true,
  },
  {
    id: 'b02ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Chicken Stew',
    description: 'Comforting, lightly spiced chicken gravy cooked with onions and whole garam masala — bone-in or boneless.',
    price: 250,
    category: 'Gravy',
    photo: '',
  },
  {
    id: 'b03ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Chicken Korma',
    description: 'Tender chicken slow-cooked in a rich yogurt and cashew-based curry — bone-in or boneless.',
    price: 250,
    category: 'Gravy',
    photo: '',
  },
  {
    id: 'c06ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Mutton Stew (2pcs)',
    description: 'Lightly spiced mutton gravy with 2 pieces, cooked with whole spices and onions.',
    price: 250,
    category: 'Gravy',
    photo: '',
  },
  {
    id: 'c07ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Mutton Stew (4pcs)',
    description: 'Lightly spiced mutton gravy with 4 pieces, cooked with whole spices and onions.',
    price: 450,
    category: 'Gravy',
    photo: '',
  },
  {
    id: 'c08ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Mutton Korma (2pcs)',
    description: 'Slow-cooked mutton in a rich yogurt and cashew-based korma gravy — 2 pieces.',
    price: 250,
    category: 'Gravy',
    photo: '',
  },
  {
    id: 'c09ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Mutton Korma (4pcs)',
    description: 'Slow-cooked mutton in a rich yogurt and cashew-based korma gravy — 4 pieces.',
    price: 450,
    category: 'Gravy',
    photo: '',
  },
  {
    id: 'b04ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Mutton Rogan Josh (2pcs)',
    description: 'Kashmiri style slow-cooked mutton in rich red onion and tomato gravy — 2 pieces.',
    price: 250,
    category: 'Gravy',
    photo: '',
  },
  {
    id: 'c10ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Mutton Rogan Josh (4pcs)',
    description: 'Kashmiri style slow-cooked mutton in rich red onion and tomato gravy — 4 pieces.',
    price: 450,
    category: 'Gravy',
    photo: '',
  },

  // ── KEBABS ───────────────────────────────────────────────────
  {
    id: 'b14ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Chicken Shami Kebab',
    description: 'Soft spiced chicken patties made with lentils, fried until golden.',
    price: 180,
    category: 'Kebabs',
    photo: '',
  },

  // ── SHAAN & TANDOOR ──────────────────────────────────────────
  {
    id: 'c11ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Murgh Malai Tikka',
    description: 'Creamy boneless chicken marinated in malai, cashew paste and mild spices, grilled in clay oven.',
    price: 250,
    category: 'Tandoor',
    photo: '',
  },
  {
    id: 'b17ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Chicken Tikka',
    description: 'Classic spiced boneless chicken chunks grilled on skewers in clay oven.',
    price: 250,
    category: 'Tandoor',
    photo: '',
  },
  {
    id: 'c12ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Chicken Afghani Barra (4pcs)',
    description: 'Thick-cut chicken pieces marinated in Afghani spices, grilled over charcoal in the tandoor.',
    price: 380,
    category: 'Tandoor',
    photo: '',
  },
  {
    id: 'c13ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Chicken Peshawari Tangdi (4pcs)',
    description: 'Whole chicken drumsticks in rich Peshawari spice blend, slow-cooked in clay oven.',
    price: 220,
    category: 'Tandoor',
    photo: '',
  },
  {
    id: 'b18ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Chicken Aatishi',
    description: 'Fiery whole chicken marinated in red spices, cooked in a clay tandoor until perfectly charred.',
    price: 300,
    category: 'Tandoor',
    photo: '/chicken-aatishi.png',
  },
  {
    id: 'b19ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Chicken Tandoori (Full)',
    description: 'Full tandoori chicken marinated in yogurt and Indian spices, roasted on skewers.',
    price: 500,
    category: 'Tandoor',
    photo: '',
  },

  // ── BREADS ───────────────────────────────────────────────────
  {
    id: 'b05ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Rumali Roti',
    description: 'Ultra-thin, soft flatbread cooked on an inverted iron griddle.',
    price: 15,
    category: 'Breads',
    photo: '',
  },
  {
    id: 'c14ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Tandoori Roti',
    description: 'Whole wheat flatbread baked in clay tandoor, soft and slightly charred.',
    price: 20,
    category: 'Breads',
    photo: '',
  },
  {
    id: 'b06ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Butter Tandoori Roti',
    description: 'Whole wheat flatbread baked in clay tandoor and brushed with fresh butter.',
    price: 25,
    category: 'Breads',
    photo: '',
  },
  {
    id: 'b07ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Lachcha Paratha',
    description: 'Layered whole wheat flatbread, crispy outside and soft inside.',
    price: 30,
    category: 'Breads',
    photo: '',
  },
  {
    id: 'c15ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Plain Naan',
    description: 'Soft leavened flatbread baked in clay tandoor.',
    price: 35,
    category: 'Breads',
    photo: '',
  },
  {
    id: 'c16ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Butter Naan',
    description: 'Soft leavened flatbread baked in clay tandoor and finished with a butter spread.',
    price: 40,
    category: 'Breads',
    photo: '',
  },
  {
    id: 'b08ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Garlic Naan',
    description: 'Fine flour leavened flatbread topped with minced garlic, baked in tandoor.',
    price: 45,
    category: 'Breads',
    photo: '',
  },
  {
    id: 'c17ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Garlic Butter Naan',
    description: 'Tandoor-baked naan loaded with minced garlic and butter for a rich, aromatic finish.',
    price: 50,
    category: 'Breads',
    photo: '',
  },

  // ── DESSERTS & BEVERAGES ─────────────────────────────────────
  {
    id: 'b20ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Lassi',
    description: 'Thick churned yogurt drink, sweetened and topped with fresh malai.',
    price: 50,
    category: 'Desserts',
    photo: '',
  },
  {
    id: 'c18ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Butter Bun',
    description: 'Soft, fluffy bun served warm with a generous spread of butter.',
    price: 35,
    category: 'Desserts',
    photo: '',
  },
  {
    id: 'b21ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Zafrani Kheer',
    description: 'Rich slow-cooked rice pudding flavoured with saffron, cardamom and sliced almonds.',
    price: 75,
    category: 'Desserts',
    photo: '',
  },
  {
    id: 'b22ed7aa-80c8-4e2e-913e-247b88a8d599',
    name: 'Shahi Tukda',
    description: 'Crispy fried bread slices soaked in saffron sugar syrup and topped with rabri.',
    price: 80,
    category: 'Desserts',
    photo: '',
  },
]

export const TOPPINGS_MAP: Record<string, { name: string; price: number }[]> = {
  'Biryani': [
    { name: 'Extra Raita', price: 20 },
    { name: 'Extra Salan / Gravy', price: 30 },
    { name: 'Double Masala', price: 40 },
  ],
  'Kebabs': [
    { name: 'Extra Mint Chutney', price: 15 },
    { name: 'Rumali Roti (1 pc)', price: 20 },
    { name: 'Special Garlic Dip', price: 25 },
  ],
  'Tandoor': [
    { name: 'Extra Mint Chutney', price: 15 },
    { name: 'Rumali Roti (1 pc)', price: 20 },
    { name: 'Special Garlic Dip', price: 25 },
  ],
  'Gravy': [
    { name: 'Extra Butter', price: 30 },
    { name: 'Garlic Naan (1 pc)', price: 40 },
    { name: 'Lachcha Paratha (1 pc)', price: 45 },
  ],
}
